---
- name: Download Spark {{ spark.version }} with hadoop {{ hadoop.version }}
  get_url:
    url=http://ftp.cc.uoc.gr/mirrors/apache/spark/spark-{{ spark.version }}/spark-{{ spark.version }}-bin-hadoop{{ hadoop.version }}.tgz
    dest={{ downloads_directory }}/spark-{{ spark.version }}-bin-hadoop{{ hadoop.version }}.tgz
- name: Extract Spark
  unarchive: 
    src={{ downloads_directory }}/spark-{{ spark.version }}-bin-hadoop{{ hadoop.version }}.tgz
    dest=/usr/local
    copy=no
- name: Create symlink
  file:
    src=/usr/local/spark-{{ spark.version }}-bin-hadoop{{ hadoop.version }}
    dest=/usr/local/spark
    state=link
- name: Add Spark to PATH
  lineinfile: dest=/etc/environment state=present backrefs=yes
              regexp='PATH=(["]*)((?!.*?/usr/local/spark/bin).*?)(["]*)$'
              line="PATH=\1\2:/usr/local/spark/bin\3"
- name: Set SPARK_HOME
  lineinfile: dest=/etc/environment
              state=present
              regexp='^SPARK_HOME'
              line='SPARK_HOME=/usr/local/spark'
- name: Set PYSPARK_PYTHON
  lineinfile: dest=/etc/environment
              state=present
              regexp='^PYSPARK_PYTHON'
              line='PYSPARK_PYTHON=python3'
